# Generated by Django 5.2.6 on 2025-10-10 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField(verbose_name='Texte original')),
                ('encrypted_text', models.TextField(verbose_name='Texte chiffré')),
                ('encryption_key', models.CharField(blank=True, max_length=255, verbose_name='Clé de chiffrement')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message chiffré',
                'verbose_name_plural': 'Messages chiffrés',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('free', 'Gratuit'), ('premium', 'Premium'), ('enterprise', 'Entreprise')], default='free', max_length=20)),
                ('subscription_date', models.DateTimeField(blank=True, null=True)),
                ('storage_limit', models.BigIntegerField(default=10485760)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Utilisateur',
                'verbose_name_plural': 'Profils Utilisateur',
            },
        ),
    ]
